---
- name: update packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: install required packages
  become: yes
  apt:
    name:
      - git
      - unzip
    state: present

- name: set timezone
  become: yes
  timezone:
    name: Europe/Paris
