- name: Update packages
  become: true
  apt:
    upgrade: true
    update_cache: true

- name: Install required packages
  become: true
  apt:
    name:
      - git
      - unzip
    state: present

- name: Install Docker key
  become: true
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Install Docker repo
  become: true
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: Install Docker
  become: true
  apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Set timezone
  become: true
  timezone:
    name: Europe/Paris

- name: Copy Whanos images
  ansible.builtin.copy:
    src: ../../../images
    dest: /whanos

- name: Copy deployment script
  ansible.builtin.copy:
    src: ../../../scripts/repository_deploy.sh
    dest: /whanos/repository_deploy.sh
