FROM maven:3.9.5-eclipse-temurin-21

WORKDIR /app

SHELL ["/bin/bash", "-c"]

COPY app/pom.xml app/
RUN cd app/ && mvn install

COPY . .
RUN cd app && mvn package

ENTRYPOINT ["java", "-jar", "app/target/app.jar"]
