FROM rust:1.74

WORKDIR /app

SHELL ["/bin/bash", "-c"]

COPY . .

RUN cargo build --release

RUN find target/release -maxdepth 1 -type f -executable -exec cp {} compiled-app \;

ENTRYPOINT ["./compiled-app"]
