FROM maven:3.9.5-eclipse-temurin-21

WORKDIR /app

SHELL ["/bin/bash", "-c"]

ONBUILD COPY app/pom.xml app/
ONBUILD RUN cd app/ && mvn install

ONBUILD COPY . .
ONBUILD RUN cd app && mvn package

ENTRYPOINT ["java", "-jar", "app/target/app.jar"]
