jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         name: admin
         password: "admin"
  systemMessage: "Welcome to Whanos"
  authorizationStrategy:
    globalMatrix:
      entries:
      - user:
          name: "admin"
          permissions:
          - "Overall/Administer"

jobs:
  - file: ./job_dsl.groovy
