jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         name: admin
         password: "admin"
  systemMessage: "Welcome to Jenkins!"
  authorizationStrategy:
    globalMatrix:
      entries:
      - user:
          name: "admin"
          permissions:
          - "Overall/Administer"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

jobs:
- file: ./job_dsl.groovy
