FROM jenkins/jenkins:lts
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=falseL
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt
COPY config.yml /var/jenkins_home/config.yml
COPY job_dsl.groovy .
ENV CASC_JENKINS_CONFIG /var/jenkins_home/config.yml
COPY ../images /var/jenkins_home/
