FROM jenkins/jenkins:lts
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
COPY plugin.txt /usr/share/jenkins/ref/plugin.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugin.txt
COPY config.yml /var/jenkins_home/config.yml
COPY job_dsl.groovy .
ENV CASC_JENKINS_CONFIG /var/jenkins_home/config.yml
