- name: Installing packets
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - git
      - unzip
      - python3-pip
      - python3
    state: present

- name: Upgrade distribution
  ignore_errors: true
  become: true
  apt:
    upgrade: dist
    update_cache: yes
    state: latest
    cache_valid_time: 3600

- name: Change timezone
  become: true
  community.general.timezone:
    name: Europe/Paris
