name: Continuous Deployment

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to production
    concurrency:
      group: ${{ github.workflow }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Ansible Playbook
        run: |
          # ansible-playbook -i ansible/inventory ansible/deploy.yml --${{ secrets.SSH_KEY }}

